Datadog: Remove support for `latest` tag (#37)
Since [Datadog chart version 3.148.2](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/CHANGELOG.md#31482), `latest` is no longer a valid identifier for agent versions (https://github.com/DataDog/helm-charts/pull/2202). 

Trying to run `datadog_up()` with no argument produces this error in Tilt:

> Error: UPGRADE FAILED: template: datadog/templates/kube-state-metrics-core-rbac.yaml:50:26: executing "datadog/templates/kube-state-metrics-core-rbac.yaml" at `<semverCompare ">=7.72.0" $imageTag>`: error calling semverCompare: invalid semantic version

While it is possible to disable these checks by scattering `doNotCheckTag: true` throughout the [`values.yaml`](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml) file, I think it makes sense to be able to rely on them to replace our own version string validation code. I checked the other repos in the DirectEmployers organization and none of them used the `agent_version` argument, so I think this change is safe.

This PR now only allows semantic version strings or `None` in the `agent_version` argument. `None` is the default and it pulls the versions specified by the chart. I also tweaked the README to be a bit nicer.

Previously: #15

- 795ab08ba59a66bd9ff44a020c6a2125aef0d74e Don't use `latest` version tag
- 1d384348b1609c41dc1b5d4ac1abbc10162941b4 Tweak README
- 51f8504cf16d44119d118208ca0bc1a6352eb0fb Remove version validation code